/*
** syscalls.c for syscalls.c in /home/uberti_l/rendu/Unix/PSU_2016_strace
**
** Made by Lous-Emile Uberti-Ares
** Login   <uberti_l@epitech.net>
**
** Started on  Wed Apr 12 21:01:38 2017 Lous-Emile Uberti-Ares
** Last update Sat Apr 15 11:16:16 2017 chalie_a
*/

#include <stdio.h>
#include "strace.h"
#include "syscalls.h"

static const	t_func	g_printable[] =
  {
    {VOID, print_void},
    {INT, print_int},
    {CHAR, print_char},
    {SIZE_T, print_size_t},
    {OFF_T, print_off_t},
    {-1, NULL}
  };

static const t_syscall	g_syscalls[] =
  {
    {__NR_read, "read", 3,  {INT, CHAR, SIZE_T, -1, -1, -1}},
    {__NR_write, "write", 3, {INT, CHAR, SIZE_T, -1, -1, -1}},
    {__NR_open, "open", 2, {CHAR, INT, -1, -1, -1, -1}},
    {__NR_close, "close", 1, {INT, -1, -1, -1, -1, -1}},
    {__NR_stat, "stat", 2, {CHAR, VOID, -1, -1, -1, -1}},
    {__NR_fstat, "fstat", 2, {INT, VOID, -1, -1, -1, -1}},
    {__NR_lstat, "lstat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_poll, "poll", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_lseek, "lseek", 3, {INT, OFF_T, INT, -1, -1, -1}},
    {__NR_mmap, "mmap", 6, {VOID, SIZE_T, INT, INT, INT, OFF_T}},
    {__NR_mprotect, "mprotect", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_munmap, "munmap", 2, {INT, INT, INT, INT, INT, INT}},
    {__NR_brk, "brk", 1, {VOID, -1, -1, -1, -1, -1}},
    {__NR_rt_sigaction, "rt_sigaction", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_rt_sigprocmask, "rt_sigprocmask", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_rt_sigreturn, "rt_sigreturn", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ioctl, "ioctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pread64, "pread64", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pwrite64, "pwrite64", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_readv, "readv", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_writev, "writev", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_access, "access", 2, {CHAR, INT, -1, -1, -1, -1}},
    {__NR_pipe, "pipe", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_select, "select", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_yield, "sched_yield", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mremap, "mremap", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_msync, "msync", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mincore, "mincore", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_madvise, "madvise", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_shmget, "shmget", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_shmat, "shmat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_shmctl, "shmctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_dup, "dup", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_dup2, "dup2", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pause, "pause", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_nanosleep, "nanosleep", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getitimer, "getitimer", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_alarm, "alarm", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setitimer, "setitimer", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getpid, "getpid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sendfile, "sendfile", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_socket, "socket", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_connect, "connect", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_accept, "accept", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sendto, "sendto", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_recvfrom, "recvfrom", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sendmsg, "sendmsg", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_recvmsg, "recvmsg", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_shutdown, "shutdown", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_bind, "bind", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_listen, "listen", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getsockname, "getsockname", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getpeername, "getpeername", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_socketpair, "socketpair", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setsockopt, "setsockopt", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getsockopt, "getsockopt", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_clone, "clone", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fork, "fork", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_vfork, "vfork", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_execve, "execve", 3, {CHAR, CHAR, CHAR, -1, -1, -1}},
    {__NR_exit, "exit", 1, {INT, -1, -1, -1, -1, -1}},
    {__NR_wait4, "wait4", 4, {INT, INT, INT, VOID, -1, -1}},
    {__NR_kill, "kill", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_uname, "uname", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_semget, "semget", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_semop, "semop", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_semctl, "semctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_shmdt, "shmdt", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_msgget, "msgget", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_msgsnd, "msgsnd", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_msgrcv, "msgrcv", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_msgctl, "msgctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fcntl, "fcntl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_flock, "flock", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fsync, "fsync", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fdatasync, "fdatasync", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_truncate, "truncate", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ftruncate, "ftruncate", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getdents, "getdents", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getcwd, "getcwd", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_chdir, "chdir", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fchdir, "fchdir", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_rename, "rename", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mkdir, "mkdir", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_rmdir, "rmdir", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_creat, "creat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_link, "link", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_unlink, "unlink", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_symlink, "symlink", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_readlink, "readlink", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_chmod, "chmod", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fchmod, "fchmod", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_chown, "chown", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fchown, "fchown", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_lchown, "lchown", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_umask, "umask", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_gettimeofday, "gettimeofday", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getrlimit, "getrlimit", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getrusage, "getrusage", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sysinfo, "sysinfo", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_times, "times", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ptrace, "ptrace", 4, {VOID, INT, VOID, VOID, -1, -1}},
    {__NR_getuid, "getuid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_syslog, "syslog", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getgid, "getgid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setuid, "setuid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setgid, "setgid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_geteuid, "geteuid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getegid, "getegid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setpgid, "setpgid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getppid, "getppid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getpgrp, "getpgrp", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setsid, "setsid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setreuid, "setreuid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setregid, "setregid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getgroups, "getgroups", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setgroups, "setgroups", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setresuid, "setresuid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getresuid, "getresuid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setresgid, "setresgid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getresgid, "getresgid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getpgid, "getpgid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setfsuid, "setfsuid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setfsgid, "setfsgid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getsid, "getsid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_capget, "capget", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_capset, "capset", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_rt_sigpending, "rt_sigpending", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_rt_sigtimedwait, "rt_sigtimedwait", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_rt_sigqueueinfo, "rt_sigqueueinfo", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_rt_sigsuspend, "rt_sigsuspend", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sigaltstack, "sigaltstack", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_utime, "utime", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mknod, "mknod", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_uselib, "uselib", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_personality, "personality", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ustat, "ustat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_statfs, "statfs", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fstatfs, "fstatfs", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sysfs, "sysfs", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getpriority, "getpriority", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setpriority, "setpriority", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_setparam, "sched_setparam", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_getparam, "sched_getparam", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_setscheduler, "sched_setscheduler", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_getscheduler, "sched_getscheduler", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_get_priority_max, "sched_get_priority_max", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_get_priority_min, "sched_get_priority_min", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_rr_get_interval, "sched_rr_get_interval", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_mlock, "mlock", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_munlock, "munlock", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mlockall, "mlockall", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_munlockall, "munlockall", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_vhangup, "vhangup", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_modify_ldt, "modify_ldt", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pivot_root, "pivot_root", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR__sysctl, "_sysctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_prctl, "prctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_arch_prctl, "arch_prctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_adjtimex, "adjtimex", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setrlimit, "setrlimit", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_chroot, "chroot", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sync, "sync", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_acct, "acct", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_settimeofday, "settimeofday", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mount, "mount", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_umount2, "umount2", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_swapon, "swapon", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_swapoff, "swapoff", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_reboot, "reboot", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sethostname, "sethostname", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setdomainname, "setdomainname", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_iopl, "iopl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ioperm, "ioperm", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_create_module, "create_module", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_init_module, "init_module", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_delete_module, "delete_module", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_get_kernel_syms, "get_kernel_syms", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_query_module, "query_module", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_quotactl, "quotactl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_nfsservctl, "nfsservctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getpmsg, "getpmsg", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_putpmsg, "putpmsg", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_afs_syscall, "afs_syscall", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_tuxcall, "tuxcall", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_security, "security", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_gettid, "gettid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_readahead, "readahead", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setxattr, "setxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_lsetxattr, "lsetxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fsetxattr, "fsetxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getxattr, "getxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_lgetxattr, "lgetxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fgetxattr, "fgetxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_listxattr, "listxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_llistxattr, "llistxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_flistxattr, "flistxattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_removexattr, "removexattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_lremovexattr, "lremovexattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fremovexattr, "fremovexattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_tkill, "tkill", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_time, "time", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_futex, "futex", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_setaffinity, "sched_setaffinity", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_getaffinity, "sched_getaffinity", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_set_thread_area, "set_thread_area", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_io_setup, "io_setup", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_io_destroy, "io_destroy", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_io_getevents, "io_getevents", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_io_submit, "io_submit", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_io_cancel, "io_cancel", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_get_thread_area, "get_thread_area", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_lookup_dcookie, "lookup_dcookie", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_epoll_create, "epoll_create", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_epoll_ctl_old, "epoll_ctl_old", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_epoll_wait_old, "epoll_wait_old", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_remap_file_pages, "remap_file_pages", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_getdents64, "getdents64", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_set_tid_address, "set_tid_address", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_restart_syscall, "restart_syscall", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_semtimedop, "semtimedop", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fadvise64, "fadvise64", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_timer_create, "timer_create", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_timer_settime, "timer_settime", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_timer_gettime, "timer_gettime", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_timer_getoverrun, "timer_getoverrun", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_timer_delete, "timer_delete", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_clock_settime, "clock_settime", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_clock_gettime, "clock_gettime", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_clock_getres, "clock_getres", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_clock_nanosleep, "clock_nanosleep", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_exit_group, "exit_group", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_epoll_wait, "epoll_wait", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_epoll_ctl, "epoll_ctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_tgkill, "tgkill", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_utimes, "utimes", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_vserver, "vserver", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mbind, "mbind", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_set_mempolicy, "set_mempolicy", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_get_mempolicy, "get_mempolicy", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mq_open, "mq_open", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mq_unlink, "mq_unlink", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mq_timedsend, "mq_timedsend", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mq_timedreceive, "mq_timedreceive", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_mq_notify, "mq_notify", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mq_getsetattr, "mq_getsetattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_kexec_load, "kexec_load", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_waitid, "waitid", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_add_key, "add_key", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_request_key, "request_key", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_keyctl, "keyctl", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ioprio_set, "ioprio_set", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ioprio_get, "ioprio_get", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_inotify_init, "inotify_init", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_inotify_add_watch, "inotify_add_watch", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_inotify_rm_watch, "inotify_rm_watch", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_migrate_pages, "migrate_pages", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_openat, "openat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mkdirat, "mkdirat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mknodat, "mknodat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fchownat, "fchownat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_futimesat, "futimesat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_newfstatat, "newfstatat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_unlinkat, "unlinkat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_renameat, "renameat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_linkat, "linkat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_symlinkat, "symlinkat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_readlinkat, "readlinkat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fchmodat, "fchmodat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_faccessat, "faccessat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pselect6, "pselect6", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_ppoll, "ppoll", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_unshare, "unshare", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_set_robust_list, "set_robust_list", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_get_robust_list, "get_robust_list", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_splice, "splice", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_tee, "tee", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sync_file_range, "sync_file_range", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_vmsplice, "vmsplice", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_move_pages, "move_pages", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_utimensat, "utimensat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_epoll_pwait, "epoll_pwait", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_signalfd, "signalfd", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_timerfd_create, "timerfd_create", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_eventfd, "eventfd", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fallocate, "fallocate", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_timerfd_settime, "timerfd_settime", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_timerfd_gettime, "timerfd_gettime", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_accept4, "accept4", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_signalfd4, "signalfd4", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_eventfd2, "eventfd2", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_epoll_create1, "epoll_create1", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_dup3, "dup3", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pipe2, "pipe2", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_inotify_init1, "inotify_init1", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_preadv, "preadv", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pwritev, "pwritev", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_rt_tgsigqueueinfo, "rt_tgsigqueueinfo", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_perf_event_open, "perf_event_open", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_recvmmsg, "recvmmsg", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fanotify_init, "fanotify_init", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_fanotify_mark, "fanotify_mark", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_prlimit64, "prlimit64", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_name_to_handle_at, "name_to_handle_at", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_open_by_handle_at, "open_by_handle_at", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_clock_adjtime, "clock_adjtime", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_syncfs, "syncfs", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sendmmsg, "sendmmsg", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_setns, "setns", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getcpu, "getcpu", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_process_vm_readv, "process_vm_readv", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_process_vm_writev, "process_vm_writev", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_kcmp, "kcmp", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_finit_module, "finit_module", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_setattr, "sched_setattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_sched_getattr, "sched_getattr", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_renameat2, "renameat2", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_seccomp, "seccomp", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_getrandom, "getrandom", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_memfd_create, "memfd_create", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_kexec_file_load, "kexec_file_load", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_bpf, "bpf", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_execveat, "execveat", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_userfaultfd, "userfaultfd", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_membarrier, "membarrier", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_mlock2, "mlock2", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_copy_file_range, "copy_file_range", 3,
     {INT, INT, INT, INT, INT, INT}},
    {__NR_preadv2, "preadv2", 3, {INT, INT, INT, INT, INT, INT}},
    {__NR_pwritev2, "pwritev2", 3, {INT, INT, INT, INT, INT, INT}},
    {-1, "", 0, {INT, INT, INT, INT, INT, INT}}
  };

static int	show_type(const t_strace *info,
			  const size_t param, const int nb_param,
			  const enum e_type type)
{
  if (nb_param > 0)
    printf(", ");
  return ((info->verbose) ? (g_printable[type].f(info->pid, param)) :
	  (printf("0x%lx", param)));
}

void		display_syscall(const t_strace *info,
				const long syscall,
				const struct user_regs_struct *regs,
				const size_t ret)
{
  int		nb;
  int		i;

  nb = -1;
  i = printf("%s(", g_syscalls[syscall].name);
  while (++nb < g_syscalls[syscall].nb_param)
    i += show_type(info, get_param(regs, nb), nb,
		   g_syscalls[syscall].params[nb]);
  i += printf(") ");
  if (41 - i > 0)
    printf("%-*s", 41 - i, " ");
  (info->verbose) ? (printf("= %ld\n", ret)) : (printf("= 0x%lx\n", ret));
}
